{% set name = "perl-mojolicious" %}
{% set version = "9.41" %}
{% set sha256 = "704fbcef2da613529b21a5b2248976a982a05ced02f85d579e9d121c40650756" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mojolicious/mojo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}
  skip: true  # [win]

requirements:
  host:
    - perl =>5.32
    - make  # [not win]

  run:
    - perl =>5.32

test:
  # Perl 'use' tests
  imports:
    - Mojolicious
    - Mojolicious::Command
    - Mojolicious::Command::Author::cpanify
    - Mojolicious::Command::Author::generate
    - Mojolicious::Command::Author::generate::app
    - Mojolicious::Command::Author::generate::dockerfile
    - Mojolicious::Command::Author::generate::lite_app
    - Mojolicious::Command::Author::generate::makefile
    - Mojolicious::Command::Author::generate::plugin
    - Mojolicious::Command::Author::inflate
    - Mojolicious::Command::cgi
    - Mojolicious::Command::daemon
    - Mojolicious::Command::eval
    - Mojolicious::Command::get
    - Mojolicious::Command::prefork
    - Mojolicious::Command::psgi
    - Mojolicious::Command::routes
    - Mojolicious::Command::version
    - Mojolicious::Commands
    - Mojolicious::Controller
    - Mojolicious::Lite
    - Mojolicious::Plugin
    - Mojolicious::Plugin::Config
    - Mojolicious::Plugin::DefaultHelpers
    - Mojolicious::Plugin::EPLRenderer
    - Mojolicious::Plugin::EPRenderer
    - Mojolicious::Plugin::HeaderCondition
    - Mojolicious::Plugin::JSONConfig
    - Mojolicious::Plugin::Mount
    - Mojolicious::Plugin::NotYAMLConfig
    - Mojolicious::Plugin::TagHelpers
    - Mojolicious::Plugins
    - Mojolicious::Renderer
    - Mojolicious::Routes
    - Mojolicious::Routes::Match
    - Mojolicious::Routes::Pattern
    - Mojolicious::Routes::Route
    - Mojolicious::Sessions
    - Mojolicious::Static
    - Mojolicious::Types
    - Mojolicious::Validator
    - Mojolicious::Validator::Validation


about:
  home: https://mojolicious.org
  license: Artistic-2.0
  license_file: LICENSE.txt
  summary: Real-time web framework
extra:
  recipe-maintainers:
    - conda-forge/perl-packagers
    - khaled196
